#--------------------------------------------#
#      _   _ _ _   ___     __    _           #
#     | | | | | |_(_) \   / /__ | |_ ___     #
#     | | | | | __| |\ \ / / _ \| __/ _ \    #
#     | |_| | | |_| | \ V / (_) | ||  __/    #
#      \___/|_|\__|_|  \_/ \___/ \__\___|    #
#                                            #
#--------------------------------------------#
#Enable offline rewards
offlinerewards: true
#NOT RECOMMENDED
offlineoprewards: false
# Messages when played executed command /vote
messages:
  - ''
  - ''
  - ''
  - ''
# Execute commands when player voted
commands:
  - 'broadcast &aThanks for voting'
  - ''
# Extras, put NONE to disable
sound: ''
effect: ''

# VISIT https://github.com/Radiance-Dev/UltiVote FOR MORE INFORMATION
# VISIT OUR DISCORD! https://discord.io/radiance

#Copyright (c) 2020 Radiance Development Team