#--------------------------------------------#
#      _   _ _ _   ___     __    _           #
#     | | | | | |_(_) \   / /__ | |_ ___     #
#     | | | | | __| |\ \ / / _ \| __/ _ \    #
#     | |_| | | |_| | \ V / (_) | ||  __/    #
#      \___/|_|\__|_|  \_/ \___/ \__\___|    #
#                                            #
#--------------------------------------------#

# Enable offline rewards
offlinerewards: true
# Enable VoteParty
voteparty: true
# The available messages
messages:
  # Called when player executes '/vote' command
  vote-message:
    - ''
    - ''
    - ''
    - ''
    - ''
  # Called when the vote reached the goal vote party
  party-message:
    - ''
party-vote:
  goal: 50
  items:
    - ''
  comands:
    - ''
  sound:
    sound-effect: ''
    volume: 5
    pitch: 5
# Called when a player has voted for the server
on-player-vote:
  # Execute given commands
  items:
    - ''
  commands:
    - 'give {player} diamond 10'
    - ''
  # The sound effects
  #
  # Extras, put NONE to disable
  sound:
    sound-effect: ''
    volume: 5
    pitch: 5

  # the effects that should be played
  effect: ''
  # the broadcast message
  broadcast:
    - ''

# DO NOT CHANGE THIS SECTION
config-version: 1
vote: 0

# VISIT https://github.com/Radiance-Dev/UltiVote FOR MORE INFORMATION
# VISIT OUR DISCORD! https://discord.io/radiance

#Copyright (c) 2020 Raznar Lab