#--------------------------------------------#
#      _   _ _ _   ___     __    _           #
#     | | | | | |_(_) \   / /__ | |_ ___     #
#     | | | | | __| |\ \ / / _ \| __/ _ \    #
#     | |_| | | |_| | \ V / (_) | ||  __/    #
#      \___/|_|\__|_|  \_/ \___/ \__\___|    #
#                                            #
#--------------------------------------------#

# Should the Vote Party feature be enabled?
# To activate a vote party the vote goals must be achieved!
vote-party: true

messages:
  # The messages sent when executing 'vote' command
  vote-message:
    - ''
    - ''
    - ''
    - ''
    - ''
  # The messages sent once the Vote Party is activated
  party-message:
    - ''

party-vote:
  # The vote goals to activate the vote party
  goal: 50
  # Items given during vote party
  items:
    - ''
  # Commands executed during vote party
  commands:
    - ''
  # Sounds played during vote party
  sound:
    sound-effect: ''
    volume: 5
    pitch: 5

# Called when a player has voted for the server
on-player-vote:
  # Items given to the player
  items:
    - ''
  # Commands executed to the player
  commands:
    - 'give {player} diamond 10'
    - ''
  # Sounds played for the player
  #
  # NOTE: put NONE to disable
  sound:
    sound-effect: ''
    volume: 5
    pitch: 5
  # Effects shown to the player
  #
  # NOTE: put NONE to disable
  effect: ''
  # The broadcast message
  broadcast:
    - ''

# DO NOT CHANGE THIS SECTION
config-version: 1
vote: 0

# VISIT https://github.com/Radiance-Dev/UltiVote FOR MORE INFORMATION
# VISIT OUR DISCORD! https://discord.io/radiance

#Copyright (c) 2020 Raznar Lab