#--------------------------------------------#
#      _   _ _ _   ___     __    _           #
#     | | | | | |_(_) \   / /__ | |_ ___     #
#     | | | | | __| |\ \ / / _ \| __/ _ \    #
#     | |_| | | |_| | \ V / (_) | ||  __/    #
#      \___/|_|\__|_|  \_/ \___/ \__\___|    #
#                                            #
#--------------------------------------------#

# Enable offline rewards
offlinerewards: true
# NOT RECOMMENDED
offlineoprewards: false

# The available messages
messages:
  # Called when player executes '/vote' command
  # todo: change this section name (i feel there's a better name)
  vote-message:
    - ''
    - ''
    - ''
    - ''
    - ''

# Called when a player has voted for the server
on-player-vote:
  # Execute given commands
  commands:
    - 'give {player} diamond 10'
    - ''
  # The sound effects
  #
  # Extras, put NONE to disable
  sound:
    sound-effect: ''
    volume: 5
    pitch: 5

  # the effects that should be played
  effect: ''
  # the broadcast message
  broadcast:
    - ''

# DO NOT CHANGE THIS
config-version: 1
data: []

# VISIT https://github.com/Radiance-Dev/UltiVote FOR MORE INFORMATION
# VISIT OUR DISCORD! https://discord.io/radiance

#Copyright (c) 2020 Raznar Lab